In [2]:
import torch

In [418]:
k = 30

In [577]:
mu = torch.randn(k,  requires_grad=True)
optimizer = torch.optim.SGD([mu], lr=1e-2)
for t in range(0,10000):
    x = torch.cat((torch.tensor([1.0]), torch.sigmoid(mu)))
    z = torch.cat((x[-1:], x[:-1])) 
    equi = x * z + (1-x) * (1-z)
    all_equi = torch.prod(equi)
    loss = -torch.log(all_equi)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
torch.round(x*100)

tensor([100.,  99.,  99.,  50.,   1.,   1.,   1.,   1.,   2.,  50.,  99.,  99.,
         99.,  99.,  50.,   1.,   1.,  50.,  99.,  99.,  99.,  99.,  99.,  99.,
         99.,  99.,  99.,  99.,  99.,  99.,  99.], grad_fn=<RoundBackward>)

In [ ]:
mu = torch.randn(k,  requires_grad=True)

In [609]:
optimizer = torch.optim.SGD([mu], lr=1e-2)
for t in range(0,10000):
    x = torch.cat((torch.tensor([1.0]), torch.sigmoid(mu)))
    all_equi = torch.prod(x) + torch.prod(1.0 - x)
    loss = -torch.log(all_equi)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
loss, torch.round(x*100)

(tensor(0.0604, grad_fn=<NegBackward>),
 tensor([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
         100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
         100., 100., 100., 100., 100., 100., 100.], grad_fn=<RoundBackward>))

In [705]:
mu = torch.randn(k,  requires_grad=True)
x = torch.cat((torch.tensor([1.0]), torch.sigmoid(mu)))
def compute_all_equi(x):
    all_equi_true = 1.0
    all_equi_false = 1.0
    for i in range(0,k+1):
        prev = i-1 % k
        all_equi_true = all_equi_true * x[i]
        all_equi_false = all_equi_false * (1-x[i])
    return all_equi_false + all_equi_true

def compute_all_equi_uncorrected(x):
    all_equi_dumb = 1.0
    for i in range(0,k+1):
        prev = i-1 % k
        all_equi_dumb = all_equi_dumb * ((x[i] * x[prev]) + (1-x[i]) * (1-x[prev]))
    return all_equi_dumb

def compute_all_equi_corrected(x):
    all_equi_dumb = 1.0
    for i in range(0,k+1):
        prev = i-1 % k
        
        all_equi_dumb = all_equi_dumb * ((x[i] * x[prev]) + (1-x[i]) * (1-x[prev]))
        all_equi_dumb += all_equi_dumb * ((x[i] * (1-x[prev])) + (1-x[i]) * x[prev])
    return all_equi_dumb

compute_all_equi_uncorrected(x), compute_all_equi(x), compute_all_equi_corrected(x)

(tensor(7.5020e-10, grad_fn=<ThMulBackward>),
 tensor(4.2494e-11, grad_fn=<ThAddBackward>),
 tensor(0.0002, grad_fn=<ThAddBackward>))

In [701]:
mu = torch.randn(k,  requires_grad=True)
optimizer = torch.optim.SGD([mu], lr=1e-1)
for t in range(0,400):
    x = torch.cat((torch.tensor([1.0]), torch.sigmoid(mu)))
#     print(x)
#     all_equi = compute_all_equi(x)
    all_equi = compute_all_equi_uncorrected(x)
    loss = -torch.log(all_equi)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
#     print(loss)

loss, torch.round(x*100)

(tensor(6.2719, grad_fn=<NegBackward>),
 tensor([100.,  99.,  99.,  98.,  50.,   3.,   1.,   1.,   1.,   1.,   2.,   2.,
           2.,   1.,   2.,  49.,  97.,  99.,  99.,  99.,  99.,  98.,  51.,   3.,
           1.,   1.,   1.,   1.,   2.,  49.,  97.], grad_fn=<RoundBackward>))

TypeError: 'Tensor' object is not callable

In [78]:
eq_12 = x[0] * x[1] + (1-x[0])*(1 - x[1])
eq_12_true = x[0] * x[1]
eq_12_false = (1-x[0]) * (1-x[1])
eq_123_true =  eq_12_true * x[2]
eq_123_false = eq_12_false * (1-x[2])
eq_23_true = x[1] * x[2]
eq_23_false = (1-x[1])*(1-x[2])
eq_123_true, eq_12_true * eq_23_true

(tensor(0.1128), tensor(0.0531))